### ISSUE TITLE
`oneOf` rule should apply to OpenAPI 2.0 only

### ISSUE THREAD

**Issue by arthurcogo** [andylockran/spectral-aws-apigateway-ruleset#9]
The ruleset currently has the following rule:

![image](https://user-images.githubusercontent.com/99221595/211425684-b461cbf4-53f6-4318-b7fa-f7ee318298f0.png)

However, the [AWS documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html) states:

> `oneOf` is not supported for OpenAPI 2.0 or SDK generation.

I have been able to use oneOf successfully in API Gateway with 3.0 which seems to confirm this.

Therefore, I suggest that this rule only applies to OpenAPI 2.0 specs.

**Comment by andylockran** [comment]
Thanks for the feedback, unfortunately due to time constraints I'd not worked out how to differentiate between the two AWS OpenAPI implementations, so am assuming that this library should only work with the v3 fork of OpenAPI.

As the AWS documentation has been updated, I will fix this by removing the warning around oneOf not being supported, and make it clearer in the README that this is only targetting openapiV3-aws.

**Comment by andylockran** [comment]
Thank you so much - this has now been released.
